db.dropDatabase();

db.createCollection("cars");
db.createCollection("users");
db.createCollection("bookings");

db.cars.insertMany([
    {
        _id: 1,
        brand: "Toyota",
        model: "Camry",
        gov_number: "A123BC777",
        status: "available",
        class: "comfort",
        color: "black",
        year: 2022,
        price_per_day: 2500,
    },
    {
        _id: 2,
        brand: "BMW",
        model: "X5",
        gov_number: "B456DE777",
        status: "rented",
        class: "premium",
        color: "white",
        year: 2020,
        price_per_day: 5000,
    },
    {
        _id: 3,
        brand: "Lada",
        model: "Vesta",
        gov_number: "C789FG777",
        status: "maintenance",
        class: "economy",
        color: "red",
        year: 2019,
        price_per_day: 1500,
    },
    {
        _id: 4,
        brand: "Kia",
        model: "Rio",
        gov_number: "E321HK777",
        status: "available",
        class: "economy",
        color: "gray",
        year: 2022,
        price_per_day: 1800,
    },
    {
        _id: 5,
        brand: "Mercedes",
        model: "E-Class",
        gov_number: "X777XX777",
        status: "available",
        class: "premium",
        color: "blue",
        year: 2023,
        price_per_day: 4500,
    },
    {
        _id: 6,
        brand: "Toyota",
        model: "Corolla",
        gov_number: "T123TO777",
        status: "available",
        class: "comfort",
        color: "silver",
        year: 2022,
        price_per_day: 2200,
    },
    {
        _id: 7,
        brand: "Hyundai",
        model: "Solaris",
        gov_number: "H456HY777",
        status: "rented",
        class: "economy",
        color: "white",
        year: 2021,
        price_per_day: 1600,
    },
    {
        _id: 8,
        brand: "Audi",
        model: "A6",
        gov_number: "A789UD777",
        status: "available",
        class: "premium",
        color: "black",
        year: 2023,
        price_per_day: 4800,
    },
    {
        _id: 9,
        brand: "Volkswagen",
        model: "Polo",
        gov_number: "V321VW777",
        status: "maintenance",
        class: "economy",
        color: "blue",
        year: 2018,
        price_per_day: 1400,
    },
    {
        _id: 10,
        brand: "Skoda",
        model: "Octavia",
        gov_number: "S654SK777",
        status: "available",
        class: "comfort",
        color: "gray",
        year: 2022,
        price_per_day: 2300,
    },
    {
        _id: 11,
        brand: "BMW",
        model: "3 Series",
        gov_number: "B987BM777",
        status: "rented",
        class: "premium",
        color: "red",
        year: 2023,
        price_per_day: 5200,
    },
    {
        _id: 12,
        brand: "Kia",
        model: "Sportage",
        gov_number: "K147KI777",
        status: "available",
        class: "comfort",
        color: "green",
        year: 2022,
        price_per_day: 2700,
    },
]);

db.users.insertMany([
    {
        _id: 1,
        first_name: "Иван",
        surname: "Петров",
        cars_rented: 2,
        age: 28,
        email: "ivan.petrov@mail.ru",
        phone: "+79161234567",
        license_number: "77AB123456",
    },
    {
        _id: 2,
        first_name: "Мария",
        surname: "Сидорова",
        cars_rented: 1,
        age: 24,
        email: "maria.sidorova@mail.ru",
        phone: "+79167654321",
        license_number: "77CD654321",
    },
    {
        _id: 3,
        first_name: "Алексей",
        surname: "Козлов",
        cars_rented: 0,
        age: 35,
        email: "alex.kozlov@mail.ru",
        phone: "+79169874563",
        license_number: "77EF789456",
    },
    {
        _id: 4,
        first_name: "Елена",
        surname: "Иванова",
        cars_rented: 1,
        age: 18,
        email: "elena.ivanova@mail.ru",
        phone: "+79163214785",
        license_number: "77GH456123",
    },
    {
        _id: 5,
        first_name: "Дмитрий",
        surname: "Смирнов",
        cars_rented: 3,
        age: 32,
        phone: "+79168527419",
        license_number: "77IJ321654",
    },
    {
        _id: 6,
        first_name: "Ольга",
        surname: "Кузнецова",
        cars_rented: 1,
        age: 29,
        email: "olga.kuznetsova@mail.ru",
        phone: "+79164785236",
        license_number: "77KL987321",
    },
    {
        _id: 7,
        first_name: "Сергей",
        surname: "Васильев",
        cars_rented: 0,
        age: 41,
        email: "sergey.vasiliev@mail.ru",
        license_number: "77MN654987",
    },
    {
        _id: 8,
        first_name: "Анна",
        surname: "Попова",
        cars_rented: 2,
        age: 26,
        license_number: "77OP147258",
    },
]);

db.bookings.insertMany([
    {
        _id: 1,
        booking_date: ISODate("2025-11-15T10:00:00Z"),
        car_id: 1,
        user_id: 1,
        cost: 2500.50,
        status: "completed",
        trips_history: [
            {
                from_address: "ул. Ленина, 15",
                to_address: "пр. Мира, 42",
                time_spent_min: 45,
                gas_spent_liters: 5.2,
                distance_km: 25.3,
            },
        ],
    },
    {
        _id: 2,
        booking_date: ISODate("2025-11-16T14:30:00Z"),
        car_id: 2,
        user_id: 2,
        cost: 5000.00,
        status: "active",
        trips_history: [
            {
                from_address: "ул. Центральная, 1",
                to_address: "аэропорт",
                time_spent_min: 120,
                gas_spent_liters: 12.8,
                distance_km: 68.5,
            },
        ],
    },
    {
        _id: 3,
        booking_date: ISODate("2025-11-17T09:15:00Z"),
        car_id: 5,
        user_id: 4,
        cost: 4500.75,
        status: "completed",
        trips_history: [
            {
                from_address: "ул. Садовая, 25",
                to_address: "ТРЦ 'Мега'",
                time_spent_min: 25,
                gas_spent_liters: 3.1,
                distance_km: 12.7,
            },
            {
                from_address: "ул. Пушкина, 10",
                to_address: "ул. Гагарина, 33",
                time_spent_min: 15,
                gas_spent_liters: 1.8,
                distance_km: 8.2,
            },
        ],
    },
    {
        _id: 4,
        booking_date: ISODate("2025-11-18T16:45:00Z"),
        car_id: 4,
        user_id: 1,
        cost: 1800.25,
        status: "completed",
        trips_history: [
            {
                from_address: "ул. Лесная, 5",
                to_address: "ул. Школьная, 18",
                time_spent_min: 35,
                gas_spent_liters: 4.5,
                distance_km: 18.9,
            },
        ],
    },
    {
        _id: 5,
        booking_date: ISODate("2025-11-19T08:00:00Z"),
        car_id: 8,
        user_id: 5,
        cost: 4800.00,
        status: "active",
        trips_history: [
            {
                from_address: "пр. Победы, 33",
                to_address: "бизнес-центр 'Скай'",
                time_spent_min: 40,
                gas_spent_liters: 4.8,
                distance_km: 22.1,
            },
        ],
    },
    {
        _id: 6,
        booking_date: ISODate("2025-11-20T11:30:00Z"),
        car_id: 6,
        user_id: 6,
        cost: 2200.00,
        status: "completed",
        trips_history: [
            {
                from_address: "ул. Мира, 12",
                to_address: "вокзал",
                time_spent_min: 20,
                gas_spent_liters: 2.3,
                distance_km: 10.5
            },
            {
                from_address: "вокзал",
                to_address: "ул. Зеленая, 45",
                time_spent_min: 15,
                gas_spent_liters: 1.7,
                distance_km: 7.8,
            },
        ],
    },
    {
        _id: 7,
        booking_date: ISODate("2025-11-21T13:15:00Z"),
        car_id: 11,
        user_id: 8,
        cost: 5200.50,
        status: "active",
        trips_history: [
            {
                from_address: "ул. Солнечная, 7",
                to_address: "деловой район",
                time_spent_min: 35,
                gas_spent_liters: 4.2,
                distance_km: 19.3,
            },
        ],
    },
    {
        _id: 8,
        booking_date: ISODate("2025-11-22T09:45:00Z"),
        car_id: 10,
        user_id: 5,
        cost: 2300.75,
        status: "completed",
        trips_history: [
            {
                from_address: "ул. Речная, 28",
                to_address: "торговый центр",
                time_spent_min: 25,
                gas_spent_liters: 2.9,
                distance_km: 13.6,
            },
            {
                from_address: "торговый центр",
                to_address: "ул. Горная, 15",
                time_spent_min: 30,
                gas_spent_liters: 3.5,
                distance_km: 16.2,
            },
        ],
    },
    {
        _id: 9,
        booking_date: ISODate("2025-11-23T16:20:00Z"),
        car_id: 12,
        user_id: 1,
        cost: 2700.00,
        status: "cancelled",
        trips_history: [],
    },
    {
        _id: 10,
        booking_date: ISODate("2025-11-24T10:10:00Z"),
        car_id: 7,
        user_id: 3,
        cost: 1600.25,
        status: "completed",
        trips_history: [
            {
                from_address: "ул. Парковая, 3",
                to_address: "супермаркет",
                time_spent_min: 15,
                gas_spent_liters: 1.6,
                distance_km: 6.8,
            },
        ],
    },
]);
